### ISSUE TITLE
Tokenizer killed all the search terms

### ISSUE THREAD

**Issue by justin-lasher** [msaari/relevanssi#14]
Hello, 

I ran into the following issue: When no search term the Tokenizer kills the search even when tax_query is provided. 

Use case, search for specific terms from additional search fields to filter results based on taxonomy.

Seems like this line 387: `/lib/search.php` should test `$search_ok` before killing. Then on line 831: `if ( $exact_match_bonus )` should change to `if ( $exact_match_bonus && !empty($q) )` because `$q` is empty.

Thanks!

**Comment by msaari** [comment]
Please expand on your use case. The behaviour seems meaningful to me, because Relevanssi just doesn't work without a search term, so the search should be killed there if there's no search terms available, otherwise you'll be running into broken MySQL queries and so on.

If you want to query posts without a search term, you're not supposed to use `relevanssi_search()` in the first place, but instead use regular WP_Query in a `relevanssi_hits_filter` function: https://www.relevanssi.com/knowledge-base/using-relevanssi-without-a-search-term/
