### ISSUE TITLE
The 7 theme search, plugin not working, shortcode can be used?

### ISSUE THREAD

**Issue by xhostcom** [msaari/relevanssi#23]
Hi, I have installed on this site being built here https://www.applifting.ml

But it doesn't bring up the portfolio types required ?

might be a bug with theme as other search also only brings up normal post types.

I think it is still using the default search not Relevanessi.

Is there a  shortcode i can insert where the default search form currently is?

Thanks

**Comment by msaari** [comment]
If you try searching with the Relevanssi admin search (Dashboard > Admin search), does that find the correct results? That's a good way to check if it's a theme issue or a setup issue.

If the admin search does find the correct results, then the problem is probably in your theme. There may be some post type filtering involved, for example. The theme support should be able to help with that.

If the admin search does not find the correct results, then the problem is likely in your indexing settings.

There's a shortcode `[searchform]`, but it won't help, as it will lead to the exact same search results page as the current search form. No difference there.
