### ISSUE TITLE
Premium 2.14.5: empty search queries are a DoS risk?

### ISSUE THREAD

**Issue by lkraav** [msaari/relevanssi#37]
We had a few incidents over the last week where empty search queries started tying up the database, with Relevanssi search query only one visible in MariaDB 10.3 process list.

I am also able to reproduce a very ineffective DB query manually: query like `https://<site>/?s` with no parameter value takes 5 seconds to complete.

There seems to be a "Redirect" feature in recent Relevanssi (Premium?), for "empty search terms", but based on the time it takes to redirect, it also performs this slow query first, then redirects.

![image](https://user-images.githubusercontent.com/147228/115846893-0aff8900-a42b-11eb-94e7-3edfd014770c.png)

PS we only display 10 results at a time, with numbered paging - should I configured Relevanssi search throttle to 10? It seems to make no sense to return 500 rows, to discard 490 every time :thinking:

**Comment by lkraav** [comment]
Further analysis shows this query seems to be inherently superslow.

I added `add_filter( 'pre_option_relevanssi_throttle_limit', function( $limit ) { return 10; } );` and query takes exactly the same 6 seconds every time.

**Comment by msaari** [comment]
Yes, this is something of a known issue, and the solution was to make sure the throttle is always enabled when there's no search term. On my test site an empty search takes 148 seconds... Looks like there's something badly wrong here, as the actual search queries take a very reasonable half a second. Removing custom excerpts reduced the time spent to 1 second, so looks like there's a bug in the excerpt-creation process when there's no search term. Thanks for bringing that to my attention.

In your case the MySQL query is slower, but about 5 seconds is not unreasonable, if the database is big enough.

Originally Relevanssi simply didn't return anything for empty search queries, which was of course much faster, but people complained as the default WP_Query behaviour is to return posts.

No, you shouldn't set the Relevanssi throttle to 10, as that would limit the total number of search results on all pages to a maximum of 10 per search term. A reasonable minimum is somewhere around 100-200, I think, as a too low value will lead to relevant posts being cut off from the results. But in general the 500 is good.

The reasoning behind `relevanssi.term = relevanssi.term` is to make the queries for no search term possible; it's also possible to not have any limits on the `term` column at all, but it was just easier to build the query this way. It also doesn't seem to make a significant difference in the speed either way.

If you're using the redirects, make sure you're using "Redirect searches without terms" – that should redirect immediately before any queries are run, because the redirecting happens in `template_redirect` hook, which happens before Relevanssi fires. "Redirect empty searches" is a different thing, this redirect happens when there are no search results found for the search.

So, I'll look at what Relevanssi is doing wrong with the excerpts, but in general I don't think empty searches are a significant risk – after all, any searches that return lots of results are going to be a potential DoS risk, but I think the responsibility for blocking excessive searching lies outside Relevanssi, Relevanssi doesn't really have the means to control that. You can use the empty query redirect to prevent the empty query searches from hogging resources.

**Comment by msaari** [comment]
"On my test site an empty search takes 148 seconds..." Actually forget that, this was caused by long PDF files and some filter load on `relevanssi_excerpt_content`. Once I removed those filters, the empty search runs in less than two seconds. Looks like there isn't a particular need to change things in the Relevanssi process, unless a scenario can be shown where there is a problem.

If empty searches are taking a long time, long posts and expensive filter functions on `relevanssi_excerpt_content` can be one cause.

**Comment by lkraav** [comment]
I have 2 sister sites where simpler, but problem site takes 5 seconds, and much heavier site takes 1-2 seconds.

I'll dig into what the difference is, but really, empty search term should be instant return. I wasn't able to achieve "instant" with configuring Relevanssi redirect, but maybe I did it wrong - will re-check and report back here.

**Comment by msaari** [comment]
That 1-2 seconds is a realistic result. Five seconds on a simpler site means there's some problem somewhere, just plain Relevanssi search should not take that long.
