### ISSUE TITLE
$progress not defined when used in wp-cli

### ISSUE THREAD

**Issue by scharc** [msaari/relevanssi#38]
I tried to wrap the cron indexing function in a small wp cli function and running into a php notice. 

The $progress is not defined if not in pro version but stull checked in normal version?

**Comment by msaari** [comment]
I'm doing this couple of times in `lib/indexing.php`:

`if ( defined( 'WP_CLI' ) && WP_CLI && $progress ) {`

But indeed it should be:

`if ( defined( 'WP_CLI' ) && WP_CLI && isset( $progress ) ) {`

(Relevanssi Premium has built-in WP CLI support for indexing.)

The fix is here: 152d9d0d1a1d93b8e212e18b8611a1214a713e2a
