### ISSUE TITLE
function relevanssi_total_queries performance problem

### ISSUE THREAD

**Issue by asakous** [msaari/relevanssi#41]
Since I have two million records on wp_relevanssi_log table.
I found that relevanssi_total_queries function  will perform very badly  on each query.
my solution is that
with add a index on time column . these query could change from 
[SELECT COUNT(id) FROM $log_table WHERE TIMESTAMPDIFF(DAY, time, NOW()) <= 1;]
to
[SELECT COUNT(id) FROM $log_table WHERE TIMESTAMPDIFF(DAY, time, NOW()) <= 1 and and time  >=  date_sub(now() , interval 2 day );]

**Comment by msaari** [comment]
My first recommendation would be: do not have two million records on `wp_relevanssi_log` table. Relevanssi has an auto-trim feature for this very purpose. It's better to keep the log trimmed to 30 days or so, because a very large log table will also make searching slower. It's better to keep the log table smaller. (If you want to keep the logs for a longer time, arrange some kind of export mechanism in it and store the old logs elsewhere.)

I'm not sure I want to add extra indices on the table. It's not very important for general Relevanssi use and the amount of database table space Relevanssi already takes is a bit of a problem, so I'm very reluctant to make it bigger for a purpose like this.

**Comment by asakous** [comment]
thanks
