### ISSUE TITLE
Improve compatibility with a strict Content Security Policy

### ISSUE THREAD

**Issue by huubl** [msaari/relevanssi#57]
The Relevanssi (Premium) plugin includes inline scripts/styles that can cause issues with setting a Content Security Policy (CSP). 

This issue proposes:

- Moving inline scripts/styles to a JS/CSS file if possible
- Or use `wp_print_inline_script_tag()` or `wp_add_inline_style()`

See:
https://make.wordpress.org/core/2021/02/23/introducing-script-attributes-related-functions-in-wordpress-5-7/

Examples:
[inline <script> tag](https://github.com/msaari/relevanssi/blob/a02f8475427c798d32aa7931e754a5649611968d/lib/interface.php#L507-L523)
Inline style tag in `/premium/templates/relevanssi-related.php`

**Comment by msaari** [comment]
The inline `<script>` tag – no problem, I've fixed that (for WP 5.7+ users).

The inline styles in the related posts are a trickier case to solve. The styles are related to a template, which may or may not be loaded. Adding a CSS file loaded when the template is used is possible, but it seems somewhat complicated. Also, part of the CSS depends on the user settings. `wp_add_inline_style()` requires a stylesheet where the inline style is added, and Relevanssi Premium has no stylesheet in itself, so that's not an option.

At the moment, I think this can be left as is. The current solution is convenient for most users, and if you need to avoid inline styles, it's easy to create a version of the template without the inline CSS and simply place the CSS in your theme stylesheet.

**Comment by huubl** [comment]
Hi @msaari 

Thanks for your reply and willing to change the inline <script> tags. For inline styles this could be a solution:

```php
function add_inline_styles() {
	$custom_css = "
		body {
			background-color: #ff0000;
		}
	";

	$handle = 'custom-inline-styles';

	wp_register_style( $handle, false ); 

	wp_add_inline_style( $handle, $custom_css );

	wp_enqueue_style( $handle );
}
add_action('wp_enqueue_scripts',  'add_inline_styles');
```

Registering a stylesheet without src (set to false) is [possible and valid](https://developer.wordpress.org/reference/functions/wp_register_style/) and Wordpress core is [using this too](https://github.com/search?q=repo%3AWordPress%2Fwordpress-develop%20wp_register_style). Using `wp_add_inline_style` makes it more easy to add a nonce.

**Comment by msaari** [comment]
I now had time to look at this. Yes, the inline styles can be changed to use `wp_add_inline_style()`, and that will be implemented in the next version. Thanks!
